server:
  port: 8081

spring:
  application:
    name: api-gateway
#  gateway:
#    routes:
#      - id: test-service
#        uri: lb:/TEST-SERVICE
#        predicates:
#          - Path=/**
#      - id: auth-service
#        uri: lb:/AUTH-SERVICE
#        predicates:
#          - Path=/influ-backend/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,beans